/**
 * Builds public/sprite.svg — the site's only icon source.
 *
 * Three inputs:
 *   - app/assets/icons/ui/*.svg     hand-drawn interface icons (stroked)
 *   - app/assets/icons/brand/*.svg  marks simple-icons no longer ships
 *   - simple-icons                  everything else, CC0, read at build time
 *
 * simple-icons is a devDependency: its paths are inlined here and it never
 * reaches the bundle. Nothing about it leaks into runtime.
 *
 * Run with `npm run icons`. The result is committed so a build never depends
 * on it.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, basename } from 'node:path'
import * as simpleIcons from 'simple-icons'

const UI_DIR = 'app/assets/icons/ui'
const BRAND_DIR = 'app/assets/icons/brand'
const OUT = 'public/sprite.svg'

/** Tech key → simple-icons slug. Keys match the --tech-* tokens. */
const TECH = {
  vue: 'vuedotjs', vuex: 'vuedotjs', pinia: 'pinia', nuxt: 'nuxt', vite: 'vite',
  react: 'react', jquery: 'jquery', p5: 'p5dotjs', bootstrap: 'bootstrap',
  angular: 'angular', java: 'openjdk', js: 'javascript', ts: 'typescript',
  sass: 'sass', html: 'html5', css: 'css', unity: 'unity', csharp: 'sharp',
  cpp: 'cplusplus', firebase: 'firebase', express: 'express', node: 'nodedotjs',
  android: 'android', docker: 'docker', postgres: 'postgresql', mysql: 'mysql',
  mongo: 'mongodb', dotnet: 'dotnet', intellij: 'intellijidea', spring: 'spring',
  gitlab: 'gitlab', github: 'github', spotify: 'spotify',
}

/** Marks drawn by hand because simple-icons dropped them. */
const LOCAL_BRAND = {
  linkedin: 'linkedin', oracle: 'oracle', vscode: 'visualstudiocode',
  illustrator: 'adobeillustrator',
}

/**
 * Trims path coordinates to 2 decimals. On a 24×24 viewBox rendered at 16–64px
 * that is well below a pixel, and simple-icons ships up to 5 — worth ~30% of
 * the sprite.
 */
const round = path => path.replace(/-?\d*\.\d{3,}/g, m => String(Math.round(Number(m) * 100) / 100))

const symbols = []
const seen = new Set()

const add = (id, attrs, body) => {
  if (seen.has(id)) throw new Error(`duplicate icon id: ${id}`)
  seen.add(id)
  symbols.push(`<symbol id="i-${id}" viewBox="0 0 24 24"${attrs}>${body}</symbol>`)
}

/** Strips the wrapper <svg> and keeps its inner markup. */
const inner = svg => svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()

for (const file of readdirSync(UI_DIR).filter(f => f.endsWith('.svg')).sort()) {
  const svg = readFileSync(join(UI_DIR, file), 'utf8')
  add(basename(file, '.svg'), ' fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"', inner(svg))
}

for (const [id, file] of Object.entries(LOCAL_BRAND)) {
  add(id, '', inner(readFileSync(join(BRAND_DIR, `${file}.svg`), 'utf8')))
}

const missing = []
for (const [id, slug] of Object.entries(TECH)) {
  if (seen.has(id)) continue
  const icon = simpleIcons[`si${slug[0].toUpperCase()}${slug.slice(1)}`]
  if (!icon) {
    missing.push(`${id} (${slug})`)
    continue
  }
  add(id, '', `<path fill="currentColor" d="${round(icon.path)}"/>`)
}

if (missing.length) {
  console.error(`✗ no source for: ${missing.join(', ')}`)
  process.exit(1)
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">
<!-- Generated by scripts/build-sprite.mjs — do not edit by hand. -->
${symbols.join('\n')}
</svg>
`

mkdirSync('public', { recursive: true })
writeFileSync(OUT, sprite)

const kb = (Buffer.byteLength(sprite) / 1024).toFixed(1)
console.log(`✓ ${OUT} — ${seen.size} icons, ${kb} kB`)

// Keeps NcIcon's union type honest: the list is generated, never typed by hand.
const names = [...seen].sort()
writeFileSync('app/utils/icon-names.ts',
  `// Generated by scripts/build-sprite.mjs — do not edit by hand.\n`
  + `export const ICON_NAMES = [\n${names.map(n => `  '${n}',`).join('\n')}\n] as const\n\n`
  + `export type IconName = (typeof ICON_NAMES)[number]\n`)
console.log(`✓ app/utils/icon-names.ts — ${names.length} names`)
